commands:
  classic:
    gains:
      front_kp: 0.4
      rear_kp: 0.5
  predictive:
    gains:
      front_kp: 0.4
      rear_kp: 0.7
    prediction:
      horizon: 10
      a0: 0.1642
      a1: 0.1072
      b1: 1.0086
      b2: -0.2801

observers:
  cinematic_linear_tangent:
    gains:
      lateral_deviation: -4
      course_deviation: -2
    filter_weights:
      lateral_deviation: 0.9
      course_deviation: 0.9
      front_sliding_angle: 0.96
      rear_sliding_angle: 0.9
  cinematic_lyapounov:
    gains:
      x_deviation: -2.
      y_deviation: -2.1
      course_deviation: -2.
      front_sliding_angle: -1.5
      rear_sliding_angle: -0.8

minimal_linear_speed_command: 0.5
automatic_linear_speed_control: true
