# path: name of the path to follow. The file must be in <config_dir>/paths.
# path: montoldre_demo4.traj
# path: montoldre_paul.traj
# path: montoldre_demo4_cross_center.traj
# path: montoldre_paul_cross_center.traj
# path: cezeaux_uturn_1.traj
path: montoldre_paul_half_north_cc.traj

# prediction_time_horizon: time to look forward on the trajectory. unit: s
prediction_time_horizon: 1.0

# path_frame_id: frame used to publish markers
# autostart: if enabled, automatically start matching after initialisation
# display: if enabled, publis rviz markers
path_frame_id: path
autostart: true
display: true
