matching:
  # path: name of the path to follow. The file must be in <config_dir>/paths.
  path: montoldre_demo4_cc.traj

  # maximal_research_radius: maximal distance to match with the trajectory. default: 10 m
  # interpolation_window_length: length of the traj piece used to compute interpolation. default 3 m
  # prediction_time_horizon: time to look forward on the trajectory. default: 0.5 s
  maximal_research_radius: 4.0
  interpolation_window_length: 3.0
  prediction_time_horizon: 1.0

  # path_frame_id: frame used to publish markers
  # autostart: if enabled, automatically start matching after initialisation
  # display: if enabled, publis rviz markers
  path_frame_id: map
  display: true

following:
  autoconfigure: true
  autostart: false
  debug: true

  base:
    type: 2FWS4WD
    inertia:
      mass: 1200.
      center: [-0.1, 0.0, 0.2]
      z_moment: 0.

  sampling_period: 10.0

  # # configuration of longitudinal control
  # longitudinal_control:
  #   minimal_linear_speed: 0.3

  # configuration for lateral control laws [classic, predictive]
  lateral_control:
    selected: classic

    classic:
      gains:
        front_kd: 0.7

    predictive:
      gains:
        front_kd: 0.4
      prediction:
        horizon: 10
        a0: 0.1642
        a1: 0.1072
        b1: 1.0086
        b2: -0.2801

  # configuration for sliding observer [none, extended_cinematic, extended_lyapunov]
  sliding_observer:
    selected: none

    extended_cinematic:
      gains:
        lateral_deviation: -4.
        course_deviation: -2.
      filter_weights:
        lateral_deviation: 0.9
        course_deviation: 0.9
        front_sliding_angle: 0.96
        rear_sliding_angle: 0.9

    extended_lyapunov:
      gains:
        x_deviation: -2.
        y_deviation: -2.1
        course_deviation: -2.
        front_sliding_angle: -1.5
        rear_sliding_angle: -0.8

  # control setpoint
  setpoint:
    desired_linear_speed: 0.5
    desired_lateral_deviation: 0.0
    desired_course_deviation: 0.0

  #configuration for cmd_mux auto connection
  cmd_output:
    # message_type: romea_mobile_base_msgs/OneAxleSteeringCommand
    message_type: ackermann_msgs/AckermannDrive
    priority: 10
    rate: 10.
  
  joy:
    buttons:
      mapping:
        stop: 1
        start: 2
    axes:
      sticks:
        mapping:
          Rear_Front_Stick: 0
          Left_Right_Stick: 1
        scale: [-1.0, 1.0]
    deadzone: 0.05
