teleop:
  axis_linear: 1
  scale_linear: 1
  scale_linear_turbo: 2
  axis_angular: 3
  scale_angular: 1.0
  enable_button: 4
  enable_turbo_button: 5
joy:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0

